---
title: "Cascade Weir Size Report"
author: 
  - "Output from the SPSC Sizer Tool v.0.1.0"
  - "Developed by the Bureau of Watershed Protection and Restoration - Anne Arundel County"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
params: 
  sitename: NA
  tab1: NA
  tab2: NA
  tab3: NA
  tab4: NA
fontsize: 10pt
geometry: "margin=1in,includefoot"
header-includes:
   - \usepackage[justification=raggedright,labelfont=bf,singlelinecheck=false]{caption}
   - \usepackage{fancyhdr}
   - \pagestyle{fancy}
   - \fancyhf{}
   - \fancyhead[R]{\small ~Page \thepage}
   - "\\fancyfoot[L]{Note: this tool is provided 'as is' without warranty of any kind, either expressed, implied, or statutory.  The user assumes the entire risk as to the quality and performance of the data from this tool.  Report is generated using user-developed and user-entered data.  Anne Arundel County makes no claims as to the validity or accuracy of the data used to develop this report or results detailed in the report.}"
---

$$\\[1in]$$


\newpage

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(leaflet)
 
```

# Data Inputs 

```{r data input summary, text,echo=FALSE,results='asis'}
cat("### Data inputs summary for ", params$sitename, "\n")

kable(params$tab1, caption = "Summary table of all cascade data inputs:",
      col.names = c("","Q\\textsubscript{100}","Q\\textsubscript{10}","Q\\textsubscript{2}"))

kable(params$tab2, caption = "Summary table of all scour depth data inputs:",
      col.names = c("",""))

```

\newpage

# Cascade Weir Sizing Results 

```{r data result summary, text,echo=FALSE,results='asis'}
cat("### Cascade weir sizing summary for ", params$sitename, "\n")

kable(params$tab3, caption = "Summary of cascade weir sizing results.",
      col.names = c("","Q\\textsubscript{100}","Q\\textsubscript{10}","Q\\textsubscript{2}"))

kable(params$tab4, caption = "Cascade weir sizing notes.",
      col.names = c("",""))

```